### ISSUE TITLE
Detected as a virus. why the tf is a GEN detected as a virus...

### ISSUE THREAD

**Issue by CoolDragon12346** [Altify-Development/Gmail-Generator-Python#5]
Hey, I tried downloading this gen, but it was detected as a virus.
I would like the gen that is not compiled into an exe so I can view it and see that it is not a virus. I saw that you are using python, and I know a good bit of it.
Thanks!
PS: sorry about my wording.

**Comment by CoolDragon12346** [comment]
BTW, im using windows, as I would rather run an exe on windows since Linux WINE is too much of a pain...

**Comment by Altify-Development** [comment]
it could be detecting the autohotkey compiler, because of the bin based encoding, it makes it look like it could do something bad, but that is because it can't decipher what the source code actually does
