### ISSUE TITLE
Trojan AHAHA :)

### ISSUE THREAD

**Issue by ewingdev** [Altify-Development/Gmail-Generator-Python#6]

**Comment by ewingdev** [comment]
![image](https://user-images.githubusercontent.com/96184300/188085109-28dad26e-e234-45e0-86b2-a341b4e46a55.png)

**Comment by Altify-Development** [comment]
literally not idiot we have talked about this look at closed issues

**Comment by ewingdev** [comment]
@Altify-Development delete my issue
