### ISSUE TITLE
Huge thanks to you for putting a virus matey! - hoes mad

### ISSUE THREAD

**Issue by GalaticDevelopment2022** [Altify-Development/Gmail-Generator-Python#7]
lmao u failed

**Comment by Altify-Development** [comment]
bruh its 0/60 on virustotal you cappin

**Comment by Altify-Development** [comment]
https://www.virustotal.com/gui/file/03f465505ded1fc79e566d7e81bd1cf33fab2876a11ec4ac7e39da238db467f7?nocache=1

**Comment by Altify-Development** [comment]
@GalaticDevelopment2022
